%interpolation -- fill in this program to complete homework 2
clear all; help interpolation;

disp(' ')
disp('Problem 1 – A simple population growth model for some species can be')
disp('approximated with the logistic equation')
disp('x_(n+1) = rho*x_n*(1 - x_n)')
disp('where x_n is the current population density and x_(n+1) is the')
disp('density some time later. The population density has a maximum value')
disp('of 1.0 and a minimum value of 0.0 (upon extinction). Rho is a')
disp('parameter that influences the population growth. As an example,')
disp('consider the case in which the initial population density is 0.5')
disp('and n is in years. Write a program to:')
disp('a - Consider population growth parameters of rho = 0.7, 1.4, 2.8,')
disp('3.1, 3.5, 3.7.')
disp('b - Generate graphs of x_n versus n for each growth parameter')
disp('with n=0, 1, … , 50.')
disp('c - Use the subplot command to graph each case in a separate subplot.')
disp('d - Use num2str along with legend to produce a legend in each')
disp('subplot identifying the growth parameter value.')

disp(' ')
disp('Problem 2 – Consider the following compounding interest formula')
disp('I = V*(R/100/k)')
disp('where V is the current value of the investment, R is the annual')
disp('interest rate, k is the number of compounding periods within a year')
disp('and I is the interest earned over the most recent compounding period')
disp('(that is added to the investment). Write a program to calculate the')
disp('period-by-period investment value for an interest rate of 10% and')
disp('for different compounding periods.')
disp('a - Consider investments that compound annually (k=1),')
disp('monthly (k=12), weekly (k=52), and daily (k=365). Assume that there')
disp('are no leap years.')
disp('b - In each case, use a while loop to calculate the increasing')
disp('investments until the initial investment quadruples.')
disp('c - Plot the growth in the investment versus time for each case')
disp('on a single plot. Be careful that the time scales are consistent.') 

disp(' ')
disp('Problem 3 – Numerical derivative of f = x*cos(x).')
disp('a - Calculate f for x=0:pi/20:3*pi.')
disp('b - Use a for loop along with if-elseif-else statements to')
disp('numerically calculate the derivative df/dx at each point.')
disp('    Calculate the derivative for the first point (i.e., x=0) based')
disp('    on the first two values.')
disp('    Calculate the derivative for the last point (i.e., x=3*pi)')
disp('    based on the last two values.')
disp('    Calculate the derivative for interior points based on the')
disp('    surrounding two values.')
disp('c - Calculate the exact value for df/dx.')
disp('d - Plot the numerical (solid) and exact (dashed) values for df/dx.')
disp('e - In a separate figure, plot the difference between the numerical')
disp('and exact values for the derivative.')

disp(' ') 
disp('Problem 4 –Modify the interpolation program (interp.m and intrpf.m)')
disp('to evaluate a Lagrange polynomial for any number of (x,y)-pairs.')
disp('Prompt the user to enter the number of points (num) and the (x,y)-pairs.')
disp('Demonstrate that your program works for num=4, with the following')
disp('(x,y)-pairs: (0,1); (1,0); (3,4); (5,3).')



